aaa:
  command_args: null
  enabled: true
  envFrom: null
  flower:
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      host: flower-api.internal.moni.com.ar
      ingressClassName: alb-ingress
  items:
  - config:
      app_location: config
      concurrency: 2
      extraArgs: -E
      loglevel: ERROR
      queues: bulk,test
    enabled: true
    extraEnvironmentVars: []
    is_beat: false
    name: bulk
    nodeSelector: null
    readinessProbe:
      command: celery inspect ping -A config -d celery@$HOSTNAME
      initialDelaySeconds: 120
      periodSeconds: 5
      timeoutSeconds: 30
    replicas: 0
    resources: {}
  nodeSelector: null
  resources: {}
back:
  affinity: null
  autoscaling:
    enabled: false
    maxReplicas: 3
    minReplicas: 1
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  commandPath: config.wsgi:application
  dev:
    enabled: true
  enabled: true
  envFrom: null
  extraEnvironmentVars: {}
  extraSecretEnvironmentVars: []
  ingress:
    annotations: 'alb.ingress.kubernetes.io/scheme: internet-facing

      alb.ingress.kubernetes.io/target-type: ip

      alb.ingress.kubernetes.io/healthcheck-port: ''8000''

      alb.ingress.kubernetes.io/success-codes: ''404''

      '
    enabled: false
    hosts:
    - host: api.example.com
      paths:
      - path: /
        pathType: Prefix
    ingressClassName: alb
    labels: {}
    tls:
      hosts:
      - api.example.com
  livenessProbe:
    enabled: false
    initialDelaySeconds: 60
    path: /v1/sys/health?standbyok=true
  nodeSelector: {}
  readinessProbe:
    enabled: false
    initialDelaySeconds: 120
    timeoutSeconds: 30
  replicas: 0
  resources: {}
  service:
    annotations: {}
    enabled: true
    healthcheck:
      enabled: false
      livenessProbe:
        enabled: true
        path: /health/ready
      readinessProbe:
        enabled: true
        path: null
    port: 8000
    targetPort: 8000
  terminationGracePeriodSeconds: 300
  tolerations: null
ccccc:
  command_args: null
  enabled: true
  envFrom: null
  flower:
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      host: flower-api.internal.moni.com.ar
      ingressClassName: alb-ingress
  items:
  - config:
      app_location: config
      concurrency: 2
      extraArgs: -E
      loglevel: ERROR
      queues: bulk,test
    enabled: true
    extraEnvironmentVars: []
    is_beat: false
    name: bulk
    nodeSelector: null
    readinessProbe:
      command: celery inspect ping -A config -d celery@$HOSTNAME
      initialDelaySeconds: 120
      periodSeconds: 5
      timeoutSeconds: 30
    replicas: 0
    resources: {}
  nodeSelector: null
  resources: {}
global:
  datadog:
    enabled: false
  enabled: true
  externalSecrets:
    enabled: false
  image:
    pullPolicy: Always
    repository: ''
    tag: latest
  namespace: example-backend-qa3
  projectName: example-backend
kkk:
  command_args: null
  enabled: true
  envFrom: null
  flower:
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      host: flower-api.internal.moni.com.ar
      ingressClassName: alb-ingress
  items:
  - config:
      app_location: config
      concurrency: 2
      extraArgs: -E
      loglevel: ERROR
      queues: bulk,test
    enabled: true
    extraEnvironmentVars: []
    is_beat: false
    name: bulk
    nodeSelector: null
    readinessProbe:
      command: celery inspect ping -A config -d celery@$HOSTNAME
      initialDelaySeconds: 120
      periodSeconds: 5
      timeoutSeconds: 30
    replicas: 0
    resources: {}
  nodeSelector: null
  resources: {}
